name: ServerCore
version: 0.1_beta
main: de.flashbeatzz.servercore.ServerCore

author: [flashbeatz, ohne_name0815]

commands:
  exp:
    description: Exp-Command
    usage: /exp <name> [<add | set | rem> <amount>]
    aliases: xp
  serverinfo:
    description: Serverinfo-Command
    usage: /serverinfo
    aliases: si
  guilde:
    description: Guilde-Command
    usage: /guilde help
